import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "tertiary-fixed": "#ffd9e4",
        "on-tertiary-fixed": "#3e0020",
        "outline": "#6f7a6a",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#becab7",
        "inverse-surface": "#343026",
        "secondary-container": "#d8e6a6",
        "background-custom": "#fff8ef",
        "on-surface": "#1e1b13",
        "primary-fixed-dim": "#91d78a",
        "tertiary": "#a52a66",
        "on-tertiary-fixed-variant": "#890f50",
        "surface-tint": "#2a6b2c",
        "surface-variant": "#e9e2d3",
        "on-secondary-fixed-variant": "#404b1b",
        "surface-container-high": "#efe7d9",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f8f0e1",
        "secondary-fixed": "#dbe9a9",
        "on-primary-container": "#f7fff1",
        "secondary": "#586330",
        "on-secondary-fixed": "#171e00",
        "inverse-primary": "#91d78a",
        "on-secondary-container": "#5c6834",
        "on-surface-variant": "#3f4a3b",
        "on-primary-fixed-variant": "#0c5216",
        "on-background": "#1e1b13",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#002203",
        "on-primary": "#ffffff",
        "primary": "#276929",
        "surface": "#fff8ef",
        "surface-bright": "#fff8ef",
        "surface-dim": "#e1d9cb",
        "surface-container": "#f5edde",
        "surface-container-low": "#fbf3e4",
        "primary-container": "#418340",
        "on-error": "#ffffff",
        "primary-fixed": "#acf4a4",
        "surface-container-highest": "#e9e2d3",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#bfcd8f",
        "tertiary-fixed-dim": "#ffb0cc",
        "tertiary-container": "#c5447f",
        "on-tertiary-container": "#fffbff",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      fontFamily: {
        "headline": ["var(--font-manrope)", "sans-serif"],
        "body": ["var(--font-inter)", "sans-serif"],
        "label": ["var(--font-inter)", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
export default config;
